FROM node:22

# Diretório de trabalho dentro do contêiner
WORKDIR /usr/src/app

# Copiar os arquivos de dependências primeiro (melhora o cache do Docker)
COPY package*.json ./

# Instalar as dependências
RUN npm install

# Copiar o restante da aplicação
COPY . .

# Expor a porta padrão da aplicação
EXPOSE 3000

# Comando para iniciar o aplicativo
CMD [ "npm", "start" ]