FROM postgres:latest

ENV POSTGRES_USER=admin
ENV POSTGRES_PASSWORD=admin_password
ENV POSTGRES_DB=satisfaction_survey

EXPOSE 5432

# Optional: Copy initialization scripts if needed
# COPY ./init-scripts/ /docker-entrypoint-initdb.d/